<a href="https://colab.research.google.com/github/theSnehaThing/FrescoPlay/blob/master/Machine_Learning_Using_Scikit_Learn_Fresco.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Machine Learning Using Scikit-Learn | 1 | Preprocessing

In [ ]:
import sklearn.datasets
import sklearn.preprocessing as preprocessing
import numpy as np
#import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
import sklearn.cluster
import sklearn.metrics



In [ ]:
iris = sklearn.datasets.load_iris()
iris_normalizer = preprocessing.Normalizer(norm = 'l2').fit(iris.data)
iris_normalized = (iris_normalizer).transform(iris.data)
print(iris_normalized.mean(axis=0))

[0.75140029 0.40517418 0.45478362 0.14107142]


In [ ]:
onehotencoder = preprocessing.OneHotEncoder()
iris_target_onehot = onehotencoder.fit_transform((iris.target).reshape(-1,1))
print(iris_target_onehot.toarray()[[0,50,100]])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
iris.data[:50,] = np.nan
data = iris.data[:50,]

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
iris_imputed = imputer.fit_transform(iris.data)
print(iris_imputed.mean(axis=0))


[6.262 2.872 4.906 1.676]


Machine Learning Using Scikit-Learn | 2 | Nearest Neighbors

In [ ]:

X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target,stratify = iris.target, random_state = 30)
print(X_train.shape)
print(X_test.shape)

(112, 4)
(38, 4)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier()
knn_classifier = knn_classifier.fit(X_train, Y_train)
print('Accuracy of Train Data :', knn_classifier.score(X_train,Y_train))
knn_classifier = knn_classifier.fit(X_test, Y_test)
print('Accuracy of Test Data :', knn_classifier.score(X_test,Y_test))

ValueError: ignored

In [ ]:
accuracy_data = {}
for i in range(3,11):
  knn_classifier = KNeighborsClassifier(n_neighbors=i)
  knn_classifier = knn_classifier.fit(X_train, Y_train)
  accuracy_data.merge({i:knn_classifier.score(X_test,Y_test)})
print(accuracy_data)
print(max(accuracy_data, key = accuracy_data.get))



ValueError: ignored

Machine Learning Using Scikit-Learn | 3 | Decision Trees

In [ ]:
np.random.seed(100)
boston = sklearn.datasets.load_boston()
X_train_boston, X_test_boston, Y_train_boston, Y_test_boston = train_test_split(boston.data, boston.target, random_state = 30)
print(X_train_boston.shape)
print(X_test_boston.shape)


(379, 13)
(127, 13)


In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt_reg = DecisionTreeRegressor(max_depth=2)
dt_reg = dt_reg.fit(X_train_boston,Y_train_boston)
print('Accuracy of Train Data :', dt_reg.score(X_train_boston,Y_train_boston))
print('Accuracy of Test Data :', dt_reg.score(X_test_boston, Y_test_boston))
y_pred = dt_reg.predict(X_test_boston[:2])
print(y_pred)


Accuracy of Train Data : 1.0
Accuracy of Test Data : 0.5873856052659214
[18.2 12.8]


In [ ]:
accuracy_boston = {}
for i in range(2,6):
  reg = DecisionTreeRegressor(max_depth=i)
  reg = reg.fit(X_train_boston,Y_train_boston)
  accuracy_boston.update({i:reg.score(X_test_boston,Y_test_boston)})
print(accuracy_boston)
print(max(accuracy_boston, key = accuracy_boston.get))


{2: 0.687610975216682, 3: 0.6962264524668584, 4: 0.5817388326168936, 5: 0.5657838515086966}
3


Machine Learning Using Scikit-Learn | 5 | SVM

In [ ]:
digits = sklearn.datasets.load_digits()
standardizer = preprocessing.StandardScaler()
digits_standardized = standardizer.fit_transform(digits.data)

X_train_digits, X_test_digits, Y_train_digits, Y_test_digits = train_test_split(digits_standardized, digits.target,stratify = digits.target, random_state = 30)
print(X_train_digits.shape)
print(X_test_digits.shape)

from sklearn.svm import SVC
svm_clf = SVC()
svm_slf = svm_clf.fit(X_train_digits,Y_train_digits)
print("Accuracy of Train set :", svm_slf.score(X_test_digits,Y_test_digits))

(1347, 64)
(450, 64)
Accuracy of Train set : 0.9733333333333334


Machine Learning Using Scikit-Learn | 6 | Clustering

In [ ]:
from sklearn.cluster import KMeans
km_cls = KMeans(n_clusters = 3)
km_cls = km_cls.fit(iris.data)
from sklearn import metrics
print(metrics.homogeneity_score(km_cls.predict(iris.data),iris.target))

from sklearn.cluster import AgglomerativeClustering
agg_cls = AgglomerativeClustering(n_clusters = 3)
agg_cls = agg_cls.fit(iris.data)
from sklearn import metrics
print(metrics.homogeneity_score(km_cls.predict(iris.data),iris.target))

from sklearn.cluster import AffinityPropagation
aff_cls = AffinityPropagation()
aff_cls = aff_cls.fit(iris.data)
from sklearn import metrics
print(metrics.homogeneity_score(km_cls.predict(iris.data),iris.target))

0.7649861514489815
0.7649861514489815
0.7649861514489815


Machine Learning Using Scikit-Learn | 4 | Ensemble Methods

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor()
rf_reg = rf_reg.fit(X_train_boston,Y_train_boston)
print('Accuracy of Train Data :', rf_reg.score(X_train_boston,Y_train_boston))
print('Accuracy of Test Data :', rf_reg.score(X_test_boston, Y_test_boston))
y_pred = dt_reg.predict(X_test_boston[:2])
print(y_pred)


Accuracy of Train Data : 0.9805124910717277
Accuracy of Test Data : 0.8903604860766346
[18.2 12.8]


In [ ]:
l = [50,100,200]
accuracy_boston_maxdepth = {}
accuracy_boston_nestimators = {}
for i in range(3,6):
  for j in l:
    reg = RandomForestRegressor(max_depth=i, n_estimators=j)
    reg = reg.fit(X_train_boston,Y_train_boston)
    accuracy_boston_nestimators.update({j:reg.score(X_test_boston,Y_test_boston)})
  accuracy_boston_maxdepth.update({i:reg.score(X_test_boston, Y_test_boston)})
#print(accuracy_boston_maxdepth, accuracy_boston_nestimators)
#print(max(accuracy_boston, key = accuracy_boston.get))
maxdepth = max(accuracy_boston_maxdepth, key = accuracy_boston_maxdepth.get)
nestimators = max(accuracy_boston_nestimators, key = accuracy_boston_nestimators.get)
a = (maxdepth, nestimators)
print(a)

(5, 100)
